export const ErrorCodes = {
    SUCCESS: 'SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    REGISTRATION_FAILED: 'REGISTRATION_FAILED',
    RECONNECT_FAIL: 'RECONNECT_FAIL',
};
