name: Publish NPM
on:
  workflow_dispatch:
jobs:
  build-and-release-framework:
    name: Build and Release Framework
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          registry-url: https://npm.pkg.github.com
      - name: Install compatible TypeScript version
        run: npm install typescript@4.9.5
        working-directory: source
      - name: Install dependencies
        run: npm install
        working-directory: source
      - name: Publish Framework to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        working-directory: source
  build-and-release-server:
    name: Build and Release Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          registry-url: https://npm.pkg.github.com
      - name: Install compatible TypeScript version
        run: npm install typescript@5.1.3
        working-directory: server
      - name: Install dependencies
        run: npm install
        working-directory: server
      - name: Update version number
        run: npm version patch
        working-directory: server
      - name: Publish Server to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        working-directory: server
