name: Publish NPM
on:
  workflow_dispatch:
jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 10.20.1
        uses: actions/setup-node@v3
        with:
          node-version: 10.20.1
      - name: Change working directory
        run: cd source
      - name: Install dependencies
        run: npm ci
        working-directory: source
      - name: Update package version
        run: npm version patch --no-git-tag-version
        working-directory: source
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: source